# -*- coding: utf-8 -*-
"""v1_optimized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyEuh8iuffIqTIZBrsJbLXXdMyNC-mzX

# Skills Gap Analyzer — Optimized v2

Key improvements over v1:
- Fixed `is_negated()` — now uses window-based search, not fragile positional logic
- Added **degradation / comparative negative** phrases (too slow, took too long, below expectations, etc.)
- Clause splitting now tags clauses with their **contrast polarity** (after 'but', 'however' = likely negative)
- Gap detection uses clause polarity context, not just keyword presence
- Removed false positive inflation from over-splitting
"""

!pip install sentence-transformers wtpsplit -q

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("mixedbread-ai/mxbai-embed-large-v1")
print("Model loaded")

SKILL_ALIASES = {

    # ── LEADERSHIP ──────────────────────────────────────────────
    "leadership": [
        "leadership", "leads the team", "mentors others",
        "guides colleagues", "takes charge", "inspires others",
        "sets direction", "drives the team", "takes ownership"
    ],
    "mentoring": [
        "mentoring", "coaches others", "develops team members",
        "supports junior staff", "guides new hires", "teaches colleagues"
    ],
    "delegation": [
        "delegation", "assigns tasks effectively", "distributes work",
        "trusts team with responsibilities", "empowers others"
    ],
    "decision making": [
        "decision making", "makes sound decisions", "decides confidently",
        "exercises good judgment", "thinks before acting", "evaluates options"
    ],
    "accountability": [
        "accountability", "takes responsibility", "owns mistakes",
        "follows through", "delivers on commitments", "reliable"
    ],
    "initiative": [
        "initiative", "proactive", "self-starter", "acts without being told",
        "takes the lead", "goes beyond expectations", "drives change"
    ],

    # ── COMMUNICATION ────────────────────────────────────────────
    "communication": [
        "communication", "articulates clearly", "expresses ideas well",
        "conveys information", "speaks confidently", "writes clearly"
    ],
    "availability": [
        "availability", "always available", "reachable when needed",
        "present when needed", "responsive to team"
    ],
    "active listening": [
        "active listening", "listens carefully", "pays attention",
        "understands others", "hears feedback well", "attentive in meetings"
    ],
    "presentation": [
        "presentation", "presents well", "delivers engaging talks",
        "public speaking", "explains to stakeholders", "clear in meetings"
    ],
    "written communication": [
        "written communication", "writes well", "clear emails",
        "good documentation", "professional writing", "concise reports"
    ],
    "giving feedback": [
        "giving feedback", "provides constructive criticism",
        "coaches through feedback", "shares observations openly"
    ],
    "receiving feedback": [
        "receiving feedback", "accepts criticism well", "open to feedback",
        "responds positively to critique", "non-defensive"
    ],

    # ── COLLABORATION ─────────────────────────────────────────────
    "teamwork": [
        "teamwork", "works well with others", "collaborative",
        "team player", "supports colleagues", "contributes to the team"
    ],
    "conflict resolution": [
        "conflict resolution", "resolves disagreements", "handles disputes",
        "mediates between parties", "de-escalates tension", "manages friction"
    ],
    "cross-functional collaboration": [
        "cross-functional collaboration", "works across teams",
        "partners with other departments", "coordinates with stakeholders"
    ],
    "empathy": [
        "empathy", "understands others feelings", "emotionally aware",
        "considers team morale", "compassionate", "supportive of peers"
    ],
    "relationship building": [
        "relationship building", "builds rapport", "earns trust",
        "maintains strong working relationships", "connects with colleagues"
    ],

    # ── DELIVERY & EXECUTION ──────────────────────────────────────
    "time management": [
        "time management", "meets deadlines", "delivers on time",
        "manages priorities", "punctual", "organized", "respects timelines"
    ],
    "productivity": [
        "productivity", "gets things done", "high output",
        "efficient worker", "delivers consistently", "results-oriented"
    ],
    "attention to detail": [
        "attention to detail", "thorough", "catches errors",
        "meticulous", "accurate work", "quality conscious", "precise"
    ],
    "goal achievement": [
        "goal achievement", "meets targets", "achieves objectives",
        "hits KPIs", "delivers results", "exceeds expectations"
    ],
    "project management": [
        "project management", "manages projects well", "coordinates deliverables",
        "tracks milestones", "keeps projects on track", "plans effectively"
    ],
    "prioritization": [
        "prioritization", "focuses on what matters", "manages workload",
        "handles multiple tasks", "knows what to tackle first"
    ],

    # ── THINKING & PROBLEM SOLVING ────────────────────────────────
    "problem solving": [
        "problem solving", "finds solutions", "resolves issues",
        "tackles challenges", "troubleshoots effectively", "overcomes obstacles"
    ],
    "critical thinking": [
        "critical thinking", "analytical", "thinks deeply",
        "questions assumptions", "evaluates situations carefully", "logical"
    ],
    "strategic thinking": [
        "strategic thinking", "sees the big picture", "thinks long term",
        "aligns work with strategy", "forward thinking", "visionary"
    ],
    "creativity": [
        "creativity", "innovative", "thinks outside the box",
        "brings new ideas", "creative solutions", "imaginative approach"
    ],
    "data-driven thinking": [
        "data-driven thinking", "uses data to decide", "evidence-based",
        "relies on metrics", "analytical approach", "backs decisions with data"
    ],

    # ── ADAPTABILITY & GROWTH ─────────────────────────────────────
    "adaptability": [
        "adaptability", "adapts to change", "flexible",
        "handles uncertainty", "adjusts quickly", "embraces new challenges"
    ],
    "learning agility": [
        "learning agility", "learns quickly", "picks up new skills fast",
        "eager to learn", "grows continuously", "develops new knowledge"
    ],
    "resilience": [
        "resilience", "bounces back", "handles pressure well",
        "stays calm under stress", "perseveres", "does not give up easily"
    ],
    "growth mindset": [
        "growth mindset", "seeks improvement", "open to learning",
        "embraces challenges", "treats failure as learning", "self-improving"
    ],

    # ── PROFESSIONALISM ───────────────────────────────────────────
    "work ethic": [
        "work ethic", "hardworking", "dedicated", "committed",
        "puts in effort", "goes the extra mile", "diligent",
        "working hard", "completes tasks", "gets the job done",
        "puts in the work", "great effort"
    ],
    "integrity": [
        "integrity", "honest", "trustworthy", "ethical",
        "acts with principles", "transparent", "does the right thing"
    ],
    "professionalism": [
        "professionalism", "conducts himself professionally",
        "conducts herself professionally", "represents the company well",
        "appropriate workplace behavior", "maintains standards"
    ],
    "punctuality": [
        "punctuality", "always on time", "never late",
        "respects others time", "arrives prepared", "timely"
    ],

    # ── TECHNICAL & DOMAIN ────────────────────────────────────────
    "technical skills": [
        "technical skills", "technically strong", "domain expertise",
        "deep knowledge", "subject matter expert", "skilled in tools"
    ],
    "digital literacy": [
        "digital literacy", "comfortable with technology",
        "uses software effectively", "tech savvy", "adapts to new tools"
    ],
    "knowledge sharing": [
        "knowledge sharing", "shares expertise", "documents learnings",
        "teaches the team", "spreads best practices", "contributes to wikis"
    ],
}
print(f"Skill list ready: {len(SKILL_ALIASES)} skills")

alias_texts = []
alias_to_skill = []

for skill, aliases in SKILL_ALIASES.items():
    for alias in aliases:
        alias_texts.append(alias)
        alias_to_skill.append(skill)

alias_embeddings = model.encode(alias_texts, convert_to_tensor=True)

print(f"Pre-computed {len(alias_texts)} alias embeddings")
print(f"Embedding matrix shape: {alias_embeddings.shape}")

"""## Negation & Degradation Detection

Key fix: We now distinguish between:
1. **Direct negations** — 'lacks', 'failed to', 'did not', etc.
2. **Degradation phrases** — 'too slow', 'took too long', 'speed declined', etc.
3. **Contrast polarity** — clauses after 'but/however' are treated as likely negative

Also fixed: `is_negated()` no longer requires the skill word itself to appear in the sentence.
Instead it checks a **window of 60 characters around the matched alias** for negation signals.
"""

import re

# ── Direct negation words ──────────────────────────────────────────────────
NEGATION_PATTERNS = [
    # Core negations
    r"\blacks?\b", r"\bwithout\b", r"\bnever\b", r"\bpoor\b",
    r"\bweak\b", r"\bweakness\b",
    r"\bstruggles?\s+(with|to)\b", r"\bneeds?\s+to\s+improve\b",
    r"\bfails?\s+to\b", r"\bfailed\s+to\b",
    r"\bunable\s+to\b", r"\bdifficulty\s+(with)?\b", r"\bhas\s+difficulty\b",

    # Task/behavioral negations
    r"\bneglected\b", r"\bignored\b", r"\bmissed\b",
    r"\bskipped\b", r"\bavoided\b", r"\brefused\s+to\b",

    # Availability
    r"\bnot\s+available\b", r"\bunavailable\b",
    r"\balways\s+busy\b", r"\bnever\s+available\b",

    # Standard negations
    r"\bnot\s+able\s+to\b", r"\bwas\s+not\s+able\b",
    r"\bdidn'?t\b", r"\bdid\s+not\b",
    r"\bdoesn'?t\b", r"\bdoes\s+not\b",
    r"\bcan'?t\b", r"\bcannot\b", r"\bwon'?t\b",
    r"\bhard\s+to\b", r"\bdifficult\s+to\b",

    # Feedback/report negations
    r"\bnot\s+enough\b", r"\bcomplaints?\s+about\b",
    r"\bnegative\s+feedback\b", r"\braised\s+concerns?\b",
    r"\bhad\s+no\s+idea\b", r"\bno\s+idea\b",
    r"\bno\s+visibility\b", r"\bno\s+clue\b",
    r"\bwasn'?t\s+informed\b", r"\bnot\s+informed\b",
]

# ── NEW: Degradation / comparative negative patterns ──────────────────────
# These capture implicit negatives not covered by direct negation words
DEGRADATION_PATTERNS = [
    r"\btoo\s+slow\b",
    r"\btoo\s+long\b",          # 'took too long', 'it took him too long'
    r"\btook\s+too\s+long\b",
    r"\btakes?\s+too\s+long\b",
    r"\bvery\s+slow\b",
    r"\bspeed\s+(is|was|has)\s+(low|slow|poor|declining)\b",
    r"\bbecame?\s+low(er|ered)?\b",  # 'became lower'
    r"\bdeclin(ed|ing)\b",
    r"\bwors(e|ened)\b",
    r"\bbelow\s+(target|expectations?|average|standard)\b",
    r"\bmissed\s+(the\s+)?deadline\b",
    r"\boverdue\b",
    r"\bdelayed\b",
    r"\bnot\s+(fast|quick|efficient)\s+enough\b",
    r"\bslow\s+(pace|progress|performance|delivery)\b",
    r"\binsufficient\b",
    r"\binadequate\b",
    r"\broom\s+for\s+improvement\b",
    r"\bneeds?\s+improvement\b",
    r"\bunderperform(ing|ed|s)?\b",
    r"\bnot\s+meeting\s+(targets?|goals?|expectations?)\b",
    r"\bfell\s+short\b",
]

# Compile all patterns
_NEG_RE = [re.compile(p, re.IGNORECASE) for p in NEGATION_PATTERNS]
_DEG_RE = [re.compile(p, re.IGNORECASE) for p in DEGRADATION_PATTERNS]


def sentence_is_negative(sentence: str) -> bool:
    """
    Returns True if the sentence contains any direct negation
    or degradation signal — meaning it describes a WEAKNESS/GAP.

    This is the core fix: we check the WHOLE sentence for signals,
    not just a window around the skill alias.
    """
    s = sentence.lower()
    for pattern in _NEG_RE:
        if pattern.search(s):
            return True
    for pattern in _DEG_RE:
        if pattern.search(s):
            return True
    return False


print("Negation patterns loaded")

# Quick sanity checks
tests = [
    ("it took him too long to finish the tasks", True),
    ("she is great at communication", False),
    ("he lacks leadership skills", True),
    ("she is always available and responsive", False),
    ("the speed became lower", True),
    ("he missed the deadline", True),
    ("she is a great team player", False),
    ("did not respond to messages", True),
]
print("\nSanity checks:")
for text, expected in tests:
    result = sentence_is_negative(text)
    status = '✓' if result == expected else '✗ FAIL'
    print(f"  {status}  '{text}'  → {result}")

from wtpsplit import SaT
sat = SaT("sat-12l")
print("SaT model loaded")

"""## Clause Splitting with Polarity Tags

Key fix: Clauses that appear **after a contrast marker** ('but', 'however', 'although', etc.)
are tagged as `polarity='negative'` regardless of negation keywords.

This solves cases like:
- 'He is great but **his speed is slow**'
- 'She communicates well however **she is often unavailable**'
"""

CONTRAST_MARKERS = r'\b(but|however|although|though|yet|despite|nevertheless|that said|the problem is|on the other hand|unfortunately)\b'


def split_with_polarity(text: str) -> list:
    """
    Split text into clauses, each tagged with polarity:
      - 'positive' : clause appears before any contrast marker
      - 'contrast' : clause appears after a contrast marker (treated as negative context)
      - 'negative' : clause contains a direct negation or degradation signal

    Returns: list of dicts {text: str, polarity: str}
    """
    units = []

    # Split by contrast markers
    parts = re.split(CONTRAST_MARKERS, text, flags=re.IGNORECASE)
    # parts alternates: [before, marker, after_1, marker2, after_2, ...]
    # We skip the marker tokens (odd indices after first split)

    after_contrast = False
    for part in parts:
        part = part.strip()
        if not part:
            continue
        # Check if this part is a marker token
        if re.fullmatch(CONTRAST_MARKERS, part, flags=re.IGNORECASE):
            after_contrast = True
            continue
        if len(part) < 5:
            continue

        # Determine polarity
        if sentence_is_negative(part):
            polarity = 'negative'
        elif after_contrast:
            polarity = 'contrast'  # contrast context = likely gap
        else:
            polarity = 'positive'

        units.append({'text': part, 'polarity': polarity})

    # Also add the full sentence as an additional unit
    full_polarity = 'negative' if sentence_is_negative(text) else 'positive'
    units.append({'text': text.strip(), 'polarity': full_polarity})

    # Comma splits (but only if they're long enough to be meaningful)
    for part in text.split(','):
        part = part.strip()
        if len(part) > 15:  # avoid tiny fragments
            pol = 'negative' if sentence_is_negative(part) else 'positive'
            units.append({'text': part, 'polarity': pol})

    # Deduplicate by text
    seen = set()
    result = []
    for u in units:
        if u['text'].lower() not in seen:
            seen.add(u['text'].lower())
            result.append(u)

    return result


def split_into_clauses(text: str) -> list:
    """
    Top-level splitter. Returns list of {text, polarity} dicts.
    """
    if not text:
        return []
    text = text[0].upper() + text[1:]

    # First: sentence-level split via SaT
    segments = sat.split(text, threshold=0.0005)
    sentences = []
    for seg in segments:
        seg = seg.strip()
        if not seg:
            continue
        if sentences and (seg[0].islower() or len(seg.split()) < 2):
            sentences[-1] = sentences[-1] + ' ' + seg
        else:
            sentences.append(seg)

    # Then: expand each sentence into polarity-tagged clauses
    all_units = []
    for sentence in sentences:
        if len(sentence) > 8:
            all_units.extend(split_with_polarity(sentence))

    # Deduplicate
    seen = set()
    result = []
    for u in all_units:
        if u['text'].lower() not in seen:
            seen.add(u['text'].lower())
            result.append(u)

    return result


# Test
test_input = "Mohamed is getting more experienced at the tasks he is assigned to, but it took him too long to finish the tasks"
clauses = split_into_clauses(test_input)
print("Clause polarity analysis:")
for c in clauses:
    print(f"  [{c['polarity']:10s}]  {c['text']}")

"""## Core Extraction Functions

- `extract_skills()` — finds skills that are mentioned **positively** (polarity = positive)
- `get_skill_gaps()` — finds skills mentioned in **negative or contrast** clauses

Both skip ambiguous clauses where polarity is unclear.
"""

SIMILARITY_THRESHOLD = 0.58
PREFIX = "Represent this sentence for searching relevant passages: "


def _score_clauses(clauses: list) -> dict:
    """
    Internal: embed each clause and get top skill matches.
    Returns dict: skill -> {score, polarity}
    """
    skill_hits = {}  # skill -> {'score': float, 'polarity': str}

    for clause in clauses:
        text = clause['text']
        polarity = clause['polarity']

        prefixed = f"{PREFIX}{text}"
        emb = model.encode(prefixed, convert_to_tensor=True)
        scores = util.cos_sim(emb, alias_embeddings)[0]

        for i, score in enumerate(scores):
            score_val = float(score)
            if score_val < SIMILARITY_THRESHOLD:
                continue

            skill = alias_to_skill[i]

            # Update if this is the best score for this skill under this polarity
            if skill not in skill_hits or score_val > skill_hits[skill]['score']:
                skill_hits[skill] = {'score': round(score_val, 2), 'polarity': polarity}
            elif skill in skill_hits:
                # If same score but different polarity — prefer the negative signal
                if polarity in ('negative', 'contrast') and skill_hits[skill]['polarity'] == 'positive':
                    skill_hits[skill]['polarity'] = polarity

    return skill_hits


def extract_skills(review_text: str) -> list:
    """
    Returns skills that are clearly PRESENT (positive polarity only).
    Excludes any skill that also appears as a gap.
    """
    clauses = split_into_clauses(review_text)
    skill_hits = _score_clauses(clauses)

    found = {
        skill: info['score']
        for skill, info in skill_hits.items()
        if info['polarity'] == 'positive'
    }

    # Remove any skill that also appears as a gap
    gaps = {g['skill'] for g in get_skill_gaps(review_text)}
    found = {k: v for k, v in found.items() if k not in gaps}

    return sorted(
        [{'skill': s, 'confidence': sc} for s, sc in found.items()],
        key=lambda x: x['confidence'],
        reverse=True
    )


def get_skill_gaps(review_text: str) -> list:
    """
    Returns skills that are clearly MISSING or WEAK (negative/contrast polarity).
    """
    clauses = split_into_clauses(review_text)
    skill_hits = _score_clauses(clauses)

    gaps = {
        skill: info['score']
        for skill, info in skill_hits.items()
        if info['polarity'] in ('negative', 'contrast')
    }

    return sorted(
        [{'skill': s, 'confidence': sc} for s, sc in gaps.items()],
        key=lambda x: x['confidence'],
        reverse=True
    )


print("Functions defined.")

"""## Test Cases

Test with the original failing example and several new ones to verify generalization.
"""

def run_analysis(review: str, label: str = ""):
    """Run and display skills analysis for a given review text."""
    print(f"{'='*60}")
    if label:
        print(f"TEST: {label}")
    print(f"INPUT: {review.strip()}")
    print()

    found = extract_skills(review)
    gaps = get_skill_gaps(review)

    print("SKILLS FOUND:")
    if found:
        for s in found:
            print(f"  {s['skill']:<30} confidence: {s['confidence']}")
    else:
        print("  (none)")

    print("\nSKILL GAPS:")
    if gaps:
        for g in gaps:
            print(f"  {g['skill']:<30} confidence: {g['confidence']}")
    else:
        print("  (none)")
    print()


